# Generated by Django 5.1.7 on 2025-03-31 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Backend", "0003_remove_tutor_student_tutor_user_alter_student_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="tutor",
        ),
        migrations.RemoveField(
            model_name="tutor",
            name="profile",
        ),
        migrations.AddField(
            model_name="student",
            name="assigned_tutors",
            field=models.ManyToManyField(
                blank=True, related_name="students_assigned", to="Backend.tutor"
            ),
        ),
        migrations.AddField(
            model_name="tutor",
            name="students",
            field=models.ManyToManyField(
                blank=True, related_name="tutors_assigned", to="Backend.student"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="tutor",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
